name: set-version
on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Get Version
        id: get-version
        run: echo "version=$(cat ise-*.sty | python .github/scripts/compute-version.py)" >> $GITHUB_OUTPUT

      - name: Get Time
        id: current-time
        run: echo "time=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
        
      - name: Zip files to release
        run: zip style.zip *.sty

      - name: Release Assets
        id: upload-release-assets
        env: 
          RELEASE_TAG: '${{ steps.get-version.outputs.version }}+${{ steps.current-time.outputs.time }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ASSETS=()
          for A in *.zip; do
            ASSETS+=("-a" "$A")
            echo "Releasing $A"
          done
            gh release create "$RELEASE_TAG" *.zip -t "$RELEASE_TAG"
