name: set-version
on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(cat ise-*.sty | python .github/scripts/compute-version.py)"

      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d-%H-%M')"
        
      - name: Zip files to release
        run: zip style.zip *.sty

      - name: Release Assets
        id: upload-release-assets
        env: 
          RELEASE_TAG: '${{ steps.get-version.outputs.version }}+${{ steps.current-time.outputs.time }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ASSETS=()
          for A in *.zip; do
            ASSETS+=("-a" "$A")
            echo "Releasing $A"
          done
          hub release create "${ASSETS[@]}" -m "$RELEASE_TAG" "$RELEASE_TAG"
